const $=id=>document.getElementById(id);
const state={assets:[],selected:0,frames:[],frame:0,playing:false,last:0,acc:0,dir:1,atlas:null,atlasJson:null,frameMeta:{},trimCache:{},previewNav:{zoom:1,x:0,y:0,enabled:false},atlasNav:{zoom:1,x:0,y:0,enabled:false}};
const extOf=n=>{const m=String(n).match(/\.[^.]+$/);return m?m[0]:'.png'};
const strip=n=>String(n).replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'_');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const status=msg=>$('globalStatus').textContent=msg;

function frameBaseName(){return strip($('renameBase').value||'Character-Action')}
function logicalSize(){let w=+$('canvasW').value||0,h=+$('canvasH').value||0;if((w<=0||h<=0)&&state.frames.length){w=w>0?w:Math.max(...state.frames.map(f=>f.sw),1);h=h>0?h:Math.max(...state.frames.map(f=>f.sh),1)}w=Math.max(1,Math.round(w||1));h=Math.max(1,Math.round(h||1));return {w,h}}
function logicalRoot(){const {w,h}=logicalSize();let x=+$('rootX').value,y=+$('rootY').value;if(!Number.isFinite(x)||$('rootX').value==='')x=Math.round(w/2);if(!Number.isFinite(y)||$('rootY').value==='')y=h-1;return {x:Math.round(x),y:Math.round(y),nx:w?x/w:0.5,ny:h?y/h:1}}
function ensureDefaults(force=false){if(!state.frames.length&&!state.assets.length)return;const maxW=state.frames.length?Math.max(...state.frames.map(f=>f.sw),1):Math.max(...state.assets.map(a=>a.w),1),maxH=state.frames.length?Math.max(...state.frames.map(f=>f.sh),1):Math.max(...state.assets.map(a=>a.h),1);if(force||!(+$('canvasW').value>0))$('canvasW').value=maxW;if(force||!(+$('canvasH').value>0))$('canvasH').value=maxH;const {w,h}=logicalSize();if(force||$('rootX').value===''||+$('rootX').value===0)$('rootX').value=Math.round(w/2);if(force||$('rootY').value===''||+$('rootY').value===0)$('rootY').value=h-1}
function frameMeta(key){if(!state.frameMeta[key])state.frameMeta[key]={ox:0,oy:0};return state.frameMeta[key]}
function currentFrame(){return state.frames[state.frame]||null}
function currentMeta(){const f=currentFrame();return f?frameMeta(f.key):{ox:0,oy:0}}
function syncOffsetInputs(){const m=currentMeta();$('offsetX').value=m.ox||0;$('offsetY').value=m.oy||0}

for(const btn of document.querySelectorAll('.tabbtn'))btn.onclick=()=>switchTab(btn.dataset.tab);
function switchTab(id){document.querySelectorAll('.tabbtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.tabpanel').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='designTab')requestAnimationFrame(()=>fitPreview(false));if(id==='atlasTab'&&state.atlas)requestAnimationFrame(()=>fitAtlas(false))}

const drop=$('drop'),fileInput=$('files');drop.onclick=()=>fileInput.click();drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');loadFiles([...e.dataTransfer.files])};fileInput.onchange=e=>loadFiles([...e.target.files]);
function loadFiles(files){const valid=files.filter(f=>f.type.startsWith('image/'));if(!valid.length)return;let pending=valid.length;status(`Loading ${valid.length} asset${valid.length===1?'':'s'}…`);for(const file of valid){const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{state.assets.push({file,url,img,originalName:file.name,name:file.name,w:img.naturalWidth,h:img.naturalHeight,id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)});pending--;if(pending===0){if(state.assets.length===valid.length){$('fw').value=state.assets[0].w;$('fh').value=state.assets[0].h}renderAssets();rebuildFrames();ensureDefaults(false);status(`${state.assets.length} asset${state.assets.length===1?'':'s'} ready`)}};img.src=url}}

function selectAsset(i){state.selected=clamp(i,0,Math.max(0,state.assets.length-1));renderAssets();if($('mode').value==='sheet'){const a=state.assets[state.selected];if(a){$('fw').value=Math.min(+$('fw').value||a.w,a.w);$('fh').value=Math.min(+$('fh').value||a.h,a.h)}}rebuildFrames()}
function deleteAsset(i){if(i<0||i>=state.assets.length)return;const [a]=state.assets.splice(i,1);if(a&&!state.assets.some(x=>x.url===a.url))URL.revokeObjectURL(a.url);state.selected=clamp(state.selected,0,Math.max(0,state.assets.length-1));renderAssets();rebuildFrames()}
function renderAssets(){const el=$('assets');el.innerHTML='';if(!state.assets.length){el.innerHTML='<div class="status">No sprites loaded yet.</div>';$('selectedInfo').textContent='Select an asset to see details.';return}state.assets.forEach((a,i)=>{const d=document.createElement('div');d.className='asset'+(i===state.selected?' active':'');d.draggable=true;d.dataset.index=i;d.innerHTML=`<div class="draghandle">⋮⋮</div><div class="assetthumb"><img src="${a.url}" alt=""></div><div class="assetmain"><div><span class="orderbadge">${i+1}</span> <span class="assetname">${esc(a.name)}</span></div><div class="assetmeta">${a.w} × ${a.h}px${a.name!==a.originalName?' · renamed':''}</div></div><div class="assetactions"><button class="small" data-act="up">↑</button><button class="small" data-act="down">↓</button><button class="small" data-act="dup">Duplicate</button><button class="small danger" data-act="del">Delete</button></div>`;d.onclick=e=>{const act=e.target.dataset.act;if(act){e.stopPropagation();if(act==='up')moveAsset(i,i-1);if(act==='down')moveAsset(i,i+1);if(act==='dup')duplicateAsset(i);if(act==='del')deleteAsset(i);return}selectAsset(i)};d.ondragstart=e=>{d.classList.add('dragging');e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move'};d.ondragend=()=>d.classList.remove('dragging');d.ondragover=e=>{e.preventDefault();d.classList.add('drop-target')};d.ondragleave=()=>d.classList.remove('drop-target');d.ondrop=e=>{e.preventDefault();d.classList.remove('drop-target');moveAsset(+e.dataTransfer.getData('text/plain'),i)};el.appendChild(d)});const a=state.assets[state.selected];$('selectedInfo').innerHTML=a?`<b>${esc(a.name)}</b><br>${a.w} × ${a.h}px<br><span class="status">Uploaded as: ${esc(a.originalName)}</span>`:'Select an asset to see details.'}
function moveAsset(from,to){if(from===to||to<0||to>=state.assets.length)return;const[a]=state.assets.splice(from,1);state.assets.splice(to,0,a);state.selected=to;renderAssets();rebuildFrames()}
function duplicateName(n){const ext=extOf(n),base=n.slice(0,-ext.length);return `${base}-copy${ext}`}
function duplicateAsset(i){const a=state.assets[i];if(!a)return;const copy={...a,id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),name:duplicateName(a.name)};state.assets.splice(i+1,0,copy);state.selected=i+1;renderAssets();rebuildFrames()}
$('duplicateSelected').onclick=()=>duplicateAsset(state.selected);$('removeSelected').onclick=()=>deleteAsset(state.selected);$('clearAll').onclick=()=>{[...new Set(state.assets.map(a=>a.url))].forEach(u=>URL.revokeObjectURL(u));state.assets=[];state.selected=0;state.frames=[];state.frameMeta={};state.trimCache={};renderAssets();renderAll()};
$('applyRename').onclick=()=>{const base=frameBaseName(),start=Math.max(0,+$('renameStart').value||0),digits=Math.max(1,+$('renameDigits').value||3);state.assets.forEach((a,i)=>a.name=`${base}-${String(start+i).padStart(digits,'0')}${extOf(a.originalName)}`);renderAssets();rebuildFrames();status('Export names applied in sequence order.')};
$('restoreNames').onclick=()=>{state.assets.forEach(a=>a.name=a.originalName);renderAssets();rebuildFrames();status('Uploaded filenames restored.')};
function downloadAsset(a){if(!a)return;fetch(a.url).then(r=>r.blob()).then(blob=>downloadBlob(blob,a.name))}
$('downloadSelected').onclick=()=>downloadAsset(state.assets[state.selected]);$('downloadAll').onclick=()=>state.assets.forEach((a,i)=>setTimeout(()=>downloadAsset(a),i*250));
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

['fw','fh','margin','spacing'].forEach(id=>$(id).addEventListener('input',rebuildFrames));
$('mode').onchange=()=>{$('sheetControls').style.display=$('mode').value==='sheet'?'block':'none';rebuildFrames()};
$('guess').onclick=()=>{const a=state.assets[state.selected];if(!a)return;const candidates=[16,24,32,40,48,64,80,96,128,160,192,256,320,384,512,640,768,1024];let best=null;for(const s of candidates){if(a.w%s===0&&a.h%s===0){const n=(a.w/s)*(a.h/s);if(n>=2&&n<=128)best={w:s,h:s,n}}}if(best){$('fw').value=best.w;$('fh').value=best.h;$('designStatus').textContent=`Guessed ${best.w}×${best.h} (${best.n} frames)`}else{$('fw').value=a.w;$('fh').value=a.h;$('designStatus').textContent='No obvious square grid found; set dimensions manually.'}rebuildFrames()};
function rebuildFrames(){const prevKey=currentFrame()?.key||null;state.frames=[];state.trimCache={};state.frame=0;state.dir=1;if(!state.assets.length){renderAll();return}if($('mode').value==='files'){state.assets.forEach((a,i)=>{const key=a.id;frameMeta(key);state.frames.push({key,img:a.img,sx:0,sy:0,sw:a.w,sh:a.h,name:strip(a.name)||`frame_${i}`,asset:a})})}else{const a=state.assets[state.selected],fw=Math.max(1,+$('fw').value||a.w),fh=Math.max(1,+$('fh').value||a.h),m=Math.max(0,+$('margin').value||0),sp=Math.max(0,+$('spacing').value||0);let n=0;for(let y=m;y+fh<=a.h-m;y+=fh+sp)for(let x=m;x+fw<=a.w-m;x+=fw+sp){const key=`${a.id}:${n}`;frameMeta(key);state.frames.push({key,img:a.img,sx:x,sy:y,sw:fw,sh:fh,name:`${strip(a.name)}_${String(n).padStart(3,'0')}`,asset:a,index:n});n++}}ensureDefaults(false);if(prevKey){const idx=state.frames.findIndex(f=>f.key===prevKey);if(idx>=0)state.frame=idx}renderAll()}

function setCanvasToMax(){if(!state.frames.length&&!state.assets.length)return;ensureDefaults(true);renderAll();status('Master canvas reset to the largest frame size.')} 
$('setCanvasMax').onclick=setCanvasToMax;
$('centerRoot').onclick=()=>{const {w,h}=logicalSize();$('rootX').value=Math.round(w/2);$('rootY').value=h-1;renderPreview();invalidateAtlas()};
['canvasW','canvasH','rootX','rootY'].forEach(id=>$(id).addEventListener('input',()=>{renderPreview();renderMetrics();invalidateAtlas()}));
$('showRoot').onchange=renderPreview;
['offsetX','offsetY'].forEach(id=>$(id).addEventListener('input',()=>{const f=currentFrame();if(!f)return;const m=frameMeta(f.key);m.ox=+$('offsetX').value||0;m.oy=+$('offsetY').value||0;renderPreview();invalidateAtlas()}));

function renderAll(){renderPreview();renderThumbs();renderMetrics();invalidateAtlas()}
function invalidateAtlas(){state.atlas=null;state.atlasJson=null;$('savePng').disabled=true;$('saveJson').disabled=true;$('atlasLayer').innerHTML='';$('atlasEmpty').style.display='grid';$('atlasStatus').textContent='Not built';$('atlasInfo').textContent='Build an atlas to see dimensions.';$('atlasMetrics').innerHTML=''}

function renderPreview(){const c=$('preview'),ctx=c.getContext('2d'),f=currentFrame();if(!f){c.width=1;c.height=1;$('hud').textContent='Frame —';$('frameText').textContent='No frames';$('designStatus').textContent='Ready';applyPreviewTransform();syncOffsetInputs();return}const {w:lw,h:lh}=logicalSize();const root=logicalRoot();const m=frameMeta(f.key);c.width=lw;c.height=lh;ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=!$('pixel').checked;ctx.strokeStyle='rgba(125,211,252,0.35)';ctx.lineWidth=1;ctx.strokeRect(.5,.5,lw-1,lh-1);ctx.drawImage(f.img,f.sx,f.sy,f.sw,f.sh,m.ox,m.oy,f.sw,f.sh);if($('showRoot').checked){ctx.save();ctx.strokeStyle='rgba(255,120,120,0.95)';ctx.fillStyle='rgba(255,120,120,0.9)';ctx.beginPath();ctx.moveTo(root.x-10,root.y+.5);ctx.lineTo(root.x+10,root.y+.5);ctx.moveTo(root.x+.5,root.y-10);ctx.lineTo(root.x+.5,root.y+10);ctx.stroke();ctx.beginPath();ctx.arc(root.x,root.y,2.5,0,Math.PI*2);ctx.fill();ctx.restore()}$('hud').textContent=`Frame ${state.frame+1}/${state.frames.length} · art ${f.sw}×${f.sh}px · logical ${lw}×${lh}px`;$('frameText').textContent=f.name;$('designStatus').textContent=`Offset ${m.ox}, ${m.oy} · Root ${root.x}, ${root.y}`;document.querySelectorAll('.thumb').forEach((t,i)=>t.classList.toggle('active',i===state.frame));syncOffsetInputs();applyPreviewTransform()}
function applyPreviewTransform(){$('previewLayer').style.transform=`translate(calc(-50% + ${state.previewNav.x}px),calc(-50% + ${state.previewNav.y}px)) scale(${state.previewNav.zoom})`;$('previewZoom').value=Math.max(1,Math.min(1000,state.previewNav.zoom*100));$('zoomLabel').textContent=formatPct(state.previewNav.zoom)}
function formatPct(z){const p=z*100;return (p<10?p.toFixed(1):Math.round(p))+'%'}
function fitPreview(resetPan=true){const f=currentFrame(),vp=$('previewViewport');if(!f)return;const {w,h}=logicalSize();const r=vp.getBoundingClientRect(),pad=24;if(r.width<2||r.height<2)return;state.previewNav.zoom=Math.max(.01,Math.min(10,Math.min((r.width-pad)/w,(r.height-pad)/h)));if(resetPan){state.previewNav.x=0;state.previewNav.y=0}applyPreviewTransform()}
$('previewZoom').oninput=()=>{state.previewNav.zoom=+$('previewZoom').value/100;applyPreviewTransform()};$('fitPreview').onclick=()=>fitPreview(true);$('actualPreview').onclick=()=>{state.previewNav.zoom=1;applyPreviewTransform()};$('resetPreviewPan').onclick=()=>{state.previewNav.x=0;state.previewNav.y=0;applyPreviewTransform()};$('pixel').onchange=()=>{renderPreview();if(state.atlas)buildAtlas()};

function setNavEnabled(kind,on){const isPreview=kind==='preview',nav=isPreview?state.previewNav:state.atlasNav,vp=$(isPreview?'previewViewport':'atlasViewport'),hint=$(isPreview?'previewHint':'atlasHint');nav.enabled=on;vp.classList.toggle('nav-enabled',on);hint.classList.toggle('on',on);hint.textContent=on?'🔓 Drag to pan · pinch to zoom':'🔒 Navigation locked'}
$('previewHint').onclick=()=>setNavEnabled('preview',!state.previewNav.enabled);$('atlasHint').onclick=()=>setNavEnabled('atlas',!state.atlasNav.enabled);
function bindPanZoom(viewport,nav,apply,zoomInput){let pointers=new Map(),startDist=0,startZoom=1,startCenter=null,startNav=null;viewport.addEventListener('pointerdown',e=>{if(!nav.enabled)return;viewport.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){startNav={x:nav.x,y:nav.y};startCenter={x:e.clientX,y:e.clientY}}else if(pointers.size===2){const pts=[...pointers.values()];startDist=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);startZoom=nav.zoom}});viewport.addEventListener('pointermove',e=>{if(!nav.enabled||!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1&&startCenter){nav.x=startNav.x+(e.clientX-startCenter.x);nav.y=startNav.y+(e.clientY-startCenter.y);apply()}else if(pointers.size===2){const pts=[...pointers.values()],dist=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);if(startDist){nav.zoom=Math.max(+zoomInput.min/100,Math.min(+zoomInput.max/100,startZoom*(dist/startDist)));apply()}}});const end=e=>{pointers.delete(e.pointerId);if(pointers.size===1){const p=[...pointers.values()][0];startCenter={...p};startNav={x:nav.x,y:nav.y}}else{startCenter=null;startNav=null;startDist=0}};viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);viewport.addEventListener('wheel',e=>{if(!nav.enabled)return;e.preventDefault();const factor=e.deltaY<0?1.1:.9;nav.zoom=Math.max(+zoomInput.min/100,Math.min(+zoomInput.max/100,nav.zoom*factor));apply()},{passive:false})}
bindPanZoom($('previewViewport'),state.previewNav,applyPreviewTransform,$('previewZoom'));

$('fps').oninput=()=>{$('fpsLabel').textContent=$('fps').value;renderMetrics();renderPreview()};$('play').onclick=()=>{state.playing=!state.playing;$('play').textContent=state.playing?'❚❚ Pause':'▶ Play'};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('first').onclick=()=>{state.frame=0;renderPreview()};$('last').onclick=()=>{state.frame=Math.max(0,state.frames.length-1);renderPreview()};
function step(d){if(!state.frames.length)return;state.frame=(state.frame+d+state.frames.length)%state.frames.length;renderPreview()}
function tick(t){if(state.playing&&state.frames.length>1){if(!state.last)state.last=t;state.acc+=t-state.last;const interval=1000/(+$('fps').value);while(state.acc>=interval){state.acc-=interval;if($('pingpong').checked){state.frame+=state.dir;if(state.frame>=state.frames.length-1){state.frame=state.frames.length-1;state.dir=-1}else if(state.frame<=0){state.frame=0;state.dir=1}}else state.frame=(state.frame+1)%state.frames.length;renderPreview()}}state.last=t;requestAnimationFrame(tick)}requestAnimationFrame(tick);

function reorderTimeline(from,to){if(from===to||from<0||to<0||from>=state.frames.length||to>=state.frames.length)return;if($('mode').value==='files'){const[a]=state.assets.splice(from,1);state.assets.splice(to,0,a);state.selected=to;renderAssets();rebuildFrames();state.frame=to;renderPreview()}else{const frame=state.frames.splice(from,1)[0];state.frames.splice(to,0,frame);state.frame=to;renderPreview();renderThumbs();renderMetrics();invalidateAtlas()}}
function renderThumbs(){const el=$('thumbs');el.innerHTML='';state.frames.forEach((f,i)=>{const d=document.createElement('div');d.className='thumb'+(i===state.frame?' active':'');d.draggable=true;d.dataset.index=i;const c=document.createElement('canvas'),sc=Math.min(52/f.sw,52/f.sh,1);c.width=Math.max(1,Math.round(f.sw*sc));c.height=Math.max(1,Math.round(f.sh*sc));const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(f.img,f.sx,f.sy,f.sw,f.sh,0,0,c.width,c.height);d.appendChild(c);const n=document.createElement('span');n.className='tn';n.textContent=i+1;d.appendChild(n);d.title=`${i+1}. ${f.name}`;d.onclick=()=>{state.frame=i;renderPreview()};d.ondragstart=e=>{d.classList.add('dragging');e.dataTransfer.setData('text/plain',String(i));e.dataTransfer.effectAllowed='move'};d.ondragend=()=>d.classList.remove('dragging');d.ondragover=e=>{e.preventDefault();d.classList.add('drop-target')};d.ondragleave=()=>d.classList.remove('drop-target');d.ondrop=e=>{e.preventDefault();d.classList.remove('drop-target');reorderTimeline(+e.dataTransfer.getData('text/plain'),i)};el.appendChild(d)})}
function renderMetrics(){const a=state.assets[state.selected],f=currentFrame(),L=logicalSize(),R=logicalRoot();$('metrics').innerHTML=`<div class="metric"><b>${state.frames.length}</b><span>frames</span></div>${a?`<div class="metric"><b>${a.w}×${a.h}</b><span>selected asset</span></div>`:''}<div class="metric"><b>${L.w}×${L.h}</b><span>logical canvas</span></div><div class="metric"><b>${$('fps').value}</b><span>FPS</span></div>`;if(!a){$('measurements').textContent='Load a sprite to see dimensions and frame counts.';return}if(f){const m=frameMeta(f.key);$('measurements').innerHTML=`Ordered frames: <code>${state.frames.length}</code><br>Current art: <code>${f.sw} × ${f.sh}px</code><br>Current offset: <code>${m.ox}, ${m.oy}</code><br>Logical canvas: <code>${L.w} × ${L.h}px</code><br>Root marker: <code>${R.x}, ${R.y}</code><br>Loop duration: <code>${(state.frames.length/(+$('fps').value)).toFixed(2)}s</code>`}}
