const $=id=>document.getElementById(id);
const state={assets:[],selected:0,frames:[],frame:0,playing:false,last:0,acc:0,dir:1,atlas:null,atlasJson:null,view:{fit:true,zoom:1,panX:0,panY:0},atlasView:{fit:true,zoom:1,panX:0,panY:0}};
for(const b of document.querySelectorAll('.tab')) b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tabpane').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab));if(b.dataset.tab==='designTab')requestAnimationFrame(()=>{applyPreviewTransform();renderPreview()});if(b.dataset.tab==='atlasTab')requestAnimationFrame(()=>applyAtlasTransform())});
const drop=$('drop'),fileInput=$('files');drop.onclick=()=>fileInput.click();drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');loadFiles([...e.dataTransfer.files])};fileInput.onchange=e=>loadFiles([...e.target.files]);
function loadFiles(files){for(const file of files.filter(f=>f.type.startsWith('image/'))){const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{state.assets.push({file,url,img,name:file.name,originalName:file.name,w:img.naturalWidth,h:img.naturalHeight,id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)});if(state.assets.length===1){state.selected=0;$('fw').value=img.naturalWidth;$('fh').value=img.naturalHeight}renderAssets();rebuildFrames();updateAssetHeader()};img.src=url}}
function updateAssetHeader(){$('assetCount').textContent=state.assets.length;$('assetModeLabel').textContent=$('mode').value==='files'?'Frames':'Sheet';$('assetStatus').textContent=state.assets.length?`${state.assets.length} asset${state.assets.length===1?'':'s'} ready`:'Ready'}
let dragIndex=null;
function renderAssets(){const el=$('assets');el.innerHTML='';if(!state.assets.length){el.innerHTML='<div class="status">No sprites loaded yet.</div>';updateAssetHeader();return}state.assets.forEach((a,i)=>{const d=document.createElement('div');d.className='asset'+(i===state.selected?' active':'');d.draggable=true;d.dataset.index=i;d.innerHTML=`<div class="handle">⋮⋮</div><div><div class="name">${esc(a.name)}</div><div class="meta">${a.w} × ${a.h}px · position ${i+1}</div></div><div class="asset-actions"><button data-act="up" title="Move up">↑</button><button data-act="down" title="Move down">↓</button><button data-act="dup" title="Duplicate">⧉</button><button data-act="del" class="danger" title="Remove">×</button></div>`;d.onclick=e=>{const act=e.target.dataset.act;if(act){e.stopPropagation();if(act==='up')moveAsset(i,i-1);if(act==='down')moveAsset(i,i+1);if(act==='dup')duplicateAsset(i);if(act==='del')removeAsset(i);return}state.selected=i;renderAssets();rebuildFrames()};d.ondragstart=e=>{dragIndex=i;d.classList.add('dragging');e.dataTransfer.effectAllowed='move'};d.ondragend=()=>{dragIndex=null;d.classList.remove('dragging')};d.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move'};d.ondrop=e=>{e.preventDefault();if(dragIndex!==null&&dragIndex!==i)moveAsset(dragIndex,i)};el.appendChild(d)});updateAssetHeader()}
function moveAsset(from,to){if(to<0||to>=state.assets.length||from===to)return;const [a]=state.assets.splice(from,1);state.assets.splice(to,0,a);state.selected=to;renderAssets();rebuildFrames();previewBatchNames()}
function duplicateAsset(i){const a=state.assets[i];const copy={...a,id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),name:incrementCopyName(a.name)};state.assets.splice(i+1,0,copy);state.selected=i+1;renderAssets();rebuildFrames();previewBatchNames()}
function incrementCopyName(n){const ext=(n.match(/\.[^.]+$/)||[''])[0],base=n.slice(0,n.length-ext.length);return `${base}-copy${ext}`}
function removeAsset(i){state.assets.splice(i,1);state.selected=Math.max(0,Math.min(state.selected,state.assets.length-1));renderAssets();rebuildFrames();previewBatchNames()}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('previewNames').onclick=previewBatchNames;$('renamePattern').oninput=previewBatchNames;$('renameStart').oninput=previewBatchNames;$('renameDigits').oninput=previewBatchNames;
function generatedNames(){const pattern=$('renamePattern').value||'Frame-##',start=+$('renameStart').value||0,digits=Math.max(1,+$('renameDigits').value||2);return state.assets.map((a,i)=>{const ext=(a.originalName||a.name).match(/\.[^.]+$/)?.[0]||'.png';const num=String(start+i).padStart(digits,'0');let base=pattern.includes('##')?pattern.replace(/##+/g,m=>String(start+i).padStart(Math.max(digits,m.length),'0')):`${pattern}-${num}`;base=base.replace(/[\\/:*?"<>|]/g,'_');return base+ext})}
function previewBatchNames(){const names=generatedNames();$('renamePreview').textContent=names.length?names.map((n,i)=>`${String(i+1).padStart(2,'0')}  ${n}`).join('\n'):'Names will preview here.'}
$('applyNames').onclick=()=>{const names=generatedNames();state.assets.forEach((a,i)=>a.name=names[i]);renderAssets();rebuildFrames();$('assetStatus').textContent='Project names updated.'};
$('downloadRenamed').onclick=()=>{if(!state.assets.length)return;const names=generatedNames();state.assets.forEach((a,i)=>setTimeout(()=>downloadBlob(a.file,names[i]),i*120));$('assetStatus').textContent='Downloading renamed copies…'};
function setMode(v){$('mode').value=v;$('designMode').value=v;$('sheetControls').style.display=v==='sheet'?'block':'none';updateAssetHeader();rebuildFrames()}
$('mode').onchange=()=>setMode($('mode').value);$('designMode').onchange=()=>setMode($('designMode').value);setMode('files');
['fw','fh','margin','spacing'].forEach(id=>$(id).addEventListener('input',rebuildFrames));
$('guess').onclick=()=>{const a=state.assets[state.selected];if(!a)return;const candidates=[16,24,32,40,48,64,80,96,128,160,192,256,320,384,512];let best=null;for(const s of candidates){if(a.w%s===0&&a.h%s===0){const n=(a.w/s)*(a.h/s);if(n>=2&&n<=64)best={w:s,h:s,n}}}if(best){$('fw').value=best.w;$('fh').value=best.h;$('status').textContent=`Guessed ${best.w}×${best.h} (${best.n} frames)`}else{$('fw').value=a.w;$('fh').value=a.h;$('status').textContent='No obvious square grid found; set dimensions manually.'}rebuildFrames()};
function strip(n){return n.replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'_')}
function rebuildFrames(){state.frames=[];state.frame=0;state.dir=1;if(!state.assets.length){renderAll();return}if($('mode').value==='files'){state.assets.forEach((a,i)=>state.frames.push({img:a.img,sx:0,sy:0,sw:a.w,sh:a.h,name:strip(a.name)||`frame_${i}`}))}else{const a=state.assets[state.selected],fw=Math.max(1,+$('fw').value||a.w),fh=Math.max(1,+$('fh').value||a.h),m=Math.max(0,+$('margin').value||0),sp=Math.max(0,+$('spacing').value||0);let n=0;for(let y=m;y+fh<=a.h-m;y+=fh+sp){for(let x=m;x+fw<=a.w-m;x+=fw+sp)state.frames.push({img:a.img,sx:x,sy:y,sw:fw,sh:fh,name:`${strip(a.name)}_${String(n++).padStart(3,'0')}`})}}renderAll()}
function renderAll(){renderPreview();renderThumbs();renderMetrics();invalidateAtlas()}